name: Deploy npm-motivation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: http://192.168.0.187:8081/repository/npm-motivation-artifacts/

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false || exit 1

      - name: Run tests
        run: npm test --maxWorkers=2 || exit 1

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: http://192.168.0.187:8081/repository/npm-motivation-artifacts/

      - name: Publish to Nexus
        run: npm publish --registry=http://192.168.0.187:8081/repository/npm-motivation-artifacts/ || exit 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  build-and-push-docker:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1

      - name: Build Docker Image
        run: docker build -t noletengine/npm-motivation:latest . || exit 1

      - name: Push Docker Image (with retry)
        run: |
          for i in {1..3}; do
            docker push noletengine/npm-motivation:latest && break || sleep 10
          done || exit 1

  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull latest image
            docker pull noletengine/npm-motivation:latest || exit 1

            # Deploy with Docker Compose
            cd ~/npm-motivation-deployment
            echo "Stopping existing container..."
            docker-compose down || exit 1
            echo "Starting new container..."
            docker-compose up -d || exit 1

