name: Deploy npm-motivation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: http://192.168.0.187:8081/repository/npm-motivation-artifacts/

      - name: Authenticate with Nexus
        run: echo "//192.168.0.187:8081/repository/npm-motivation-artifacts/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies (with Fallback)
        run: |
          export NPM_CONFIG_FETCH_TIMEOUT=180000
          export NPM_CONFIG_MAX_SOCKETS=10
          mkdir -p ~/.npm-cache

          echo "Installing from Nexus..."
          for i in {1..3}; do
            npm ci --prefer-offline --cache ~/.npm-cache --no-audit --progress=false --legacy-peer-deps && break || sleep 10
          done || {
            echo "Fallback: Installing from npmjs.org..."
            npm ci --registry=https://registry.npmjs.org/ --prefer-offline --cache ~/.npm-cache --no-audit --progress=false --legacy-peer-deps || exit 1
          }

      - name: Run Tests (Optimized)
        run: npm test --maxWorkers=2 || exit 1

  publish-npm:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: http://192.168.0.187:8081/repository/npm-motivation-artifacts/

      - name: Authenticate with Nexus
        run: echo "//192.168.0.187:8081/repository/npm-motivation-artifacts/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Publish to Nexus (with Auto-Retry)
        run: |
          echo "Publishing package..."
          for i in {1..3}; do
            npm publish --registry=http://192.168.0.187:8081/repository/npm-motivation-artifacts/ && break || sleep 10
          done || exit 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  build-and-push-docker:
    needs: publish-npm
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub (Auto-Retry)
        run: |
          echo "Logging into Docker Hub..."
          for i in {1..3}; do
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin && break || sleep 10
          done || exit 1

      - name: Build Optimized Docker Image
        run: |
          echo "Building Docker image..."
          docker build --pull --rm --no-cache -t noletengine/npm-motivation:latest . || exit 1

      - name: Push Docker Image (Auto-Retry)
        run: |
          echo "Pushing Docker image..."
          for i in {1..3}; do
            docker push noletengine/npm-motivation:latest && break || sleep 10
          done || exit 1

  deploy:
    needs: build-and-push-docker
    runs-on: self-hosted
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Checking if container is running..."
            if docker ps -q -f name=npm-motivation | grep -q .; then
              echo "Stopping old container..."
              docker stop npm-motivation
              docker rm npm-motivation
            fi

            echo "Pulling latest Docker image..."
            docker pull noletengine/npm-motivation:latest || exit 1

            echo "Deploying with Docker Compose..."
            cd ~/npm-motivation-deployment
            docker-compose down || exit 1
            docker-compose up -d || exit 1

            echo "Ensuring the service is running..."
            sleep 5
            curl -I http://localhost:3000 || exit 1

