name: Deploy npm-motivation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Build Version
        run: echo "BUILD_VERSION=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: http://192.168.0.187:8081/repository/npm-motivation-artifacts/

      - name: Authenticate with Nexus (Using Username & Password)
        run: |
          echo "registry=http://192.168.0.187:8081/repository/npm-motivation-artifacts/" > ~/.npmrc
          echo "_auth=$(echo -n '${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}' | base64)" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          echo "email=nolet7@gmail.com" >> ~/.npmrc
          cat ~/.npmrc

      - name: Install Dependencies & Jest
        run: |
          npm ci --prefer-offline --legacy-peer-deps
          npm install --save-dev jest

      - name: Run Tests
        run: npm test --maxWorkers=2 || exit 1

  build-and-push-docker:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Package from Nexus
        run: |
          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" -O \
          "http://192.168.0.187:8081/repository/npm-motivation-artifacts/npm-motivation-${{ env.BUILD_VERSION }}.tgz"
          ls -lh
          tar -xzf npm-motivation-${{ env.BUILD_VERSION }}.tgz

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          echo "Building Docker image with version $BUILD_VERSION"
          docker build --pull --rm --no-cache -t noletengine/npm-motivation:latest .
          docker tag noletengine/npm-motivation:latest noletengine/npm-motivation:$BUILD_VERSION

          docker push noletengine/npm-motivation:latest
          docker push noletengine/npm-motivation:$BUILD_VERSION

